{% set name = "jsonargparse" %}
{% set version = "4.27.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jsonargparse-{{ version }}.tar.gz
  sha256: ebd2e0a4faef85a075bb6ef79c6b2f03f57a5f8e3db26c911b55518a1bca68ad

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install .[all] -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - pyyaml >=3.13
    - docstring_parser >=0.7.3
    - dataclasses >=0.8
    - jsonschema >=3.2.0
    - jsonnet >=0.13.0
    - validators >=0.14.2
    - requests >=2.18.4
    - fsspec >=0.8.4
    - argcomplete >=2.0.0

test:
  imports:
    - jsonargparse
    - jsonargparse_tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/omni-us/jsonargparse
  summary: Parsing of command line options, yaml/jsonnet config files and/or environment variables based on argparse.
  license: MIT
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - olegtarasov
